pipeline:
  astronomer-cloud-dev:
    image: alpine
    secrets: [ google_application_credentials ]
    commands:
    - apk --update add git terraform
    - apk add --no-cache ca-certificates openssl
    - export GOOGLE_CREDENTIALS=$${GOOGLE_APPLICATION_CREDENTIALS}
    - cd astronomer-cloud-dev
    - terraform init
    - terraform validate
    - terraform apply -auto-approve

  notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    webhook: $${slack_webhook}
    channel: platform
    when:
      status: [ failure, changed ]
