pipeline:
  astronomer-cloud-dev-tf-apply:
    image: alpine
    secrets: [ google_application_credentials ]
    commands:
      - apk --update add git curl wget
      - curl --silent --output terraform.zip "https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip"
      - unzip terraform.zip -d /usr/bin ; rm -f terraform.zip; export PATH="$PATH:/usr/bin"
      - apk add --no-cache ca-certificates openssl
      - export GOOGLE_CREDENTIALS=$${GOOGLE_APPLICATION_CREDENTIALS}
      - cd astronomer-cloud-dev
      - terraform init
      - terraform validate
      - terraform apply -auto-approve

  astronomer-cloud-dev-tf-destroy:
    image: alpine
    secrets: [ google_application_credentials ]
    commands:
      - apk --update add git curl wget
      - curl --silent --output terraform.zip "https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip"
      - unzip terraform.zip -d /usr/bin ; rm -f terraform.zip; export PATH="$PATH:/usr/bin"
      - export GOOGLE_CREDENTIALS=$${GOOGLE_APPLICATION_CREDENTIALS}
      - cd astronomer-cloud-dev
      - terraform destroy -auto-approve
    when:
      status: [ failure, success ]

  notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    webhook: $${slack_webhook}
    channel: platform
    when:
      status: [ failure, changed ]
